query GetPlannerItems($startDate: String!, $endDate: String!) {
	getPlannerItems(startDate: $startDate, endDate: $endDate) {
		id
		dishId
		date
		mealTime
		dish {
			id
			name
			category
			imageUrl
			calories
			fat
			carbs
			description
			ingredients {
				name
				amount
				productId
				product {
					category
				}
			}
		}
	}
}

mutation SavePlannerItems(
	$items: [PlannerItemInput!]!
	$startDate: String!
	$endDate: String!
) {
	savePlanner(items: $items, startDate: $startDate, endDate: $endDate)
}
