query Me {
	me {
		id
		email
		isEmailVerified
		name
		avatar
		phone
		role
		diet
		allergy
		dislike
		createdAt
		updatedAt
		dishesCount
		productsCount
		favoriteProducts {
			id
		}
		favoriteDishes {
			id
		}
	}
}

mutation UpdateProfile(
	$name: String
	$phone: String
	$avatar: String
	$diet: String
	$allergy: [String!]
	$dislike: [String!]
) {
	updateProfile(
		name: $name
		phone: $phone
		avatar: $avatar
		diet: $diet
		allergy: $allergy
		dislike: $dislike
	) {
		id
		email
		name
		role
		avatar
		phone
		diet
		allergy
		dislike
		createdAt
		updatedAt
	}
}

mutation ChangePassword($currentPassword: String!, $newPassword: String!) {
	changePassword(currentPassword: $currentPassword, newPassword: $newPassword)
}

mutation ResendVerificationEmail {
	resendVerificationEmail
}
